name: CI

on: 
  push:
    branches: [ master ]
    paths:
    - 'dlib/**'
    - 'dub.json'
    - '.github/workflows/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'dlib/**'
    - 'dub.json'
    - '.github/workflows/**'

jobs:
  test:
    name: Dub Tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dc: [dmd-latest, ldc-latest, dmd-2.094.2, ldc-1.24.0]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}
      - name: Run tests
        run: dub test --build=unittest-cov
      - name: Run code coverage
        if: success()
        run: |
          curl https://codecov.io/bash > codecov.sh
          bash codecov.sh
